### ISSUE TITLE
Adding a obstacle map lib

### ISSUE THREAD

**Issue by SalahEddineGhamri** [rsasaki0109/rust_robotics#4]
Since a lot of robotics algorithm will take place in 2D environment.
We need an obstacle_map that the user can define it easily. 
it will contains obstacles locations. it is simply a matrix where obstacles takes the values of "1". 
This obstacle_map will be used by multiple algorithms thus better add it in `lib.rs`

**Comment by rsasaki0109** [comment]
This issue will be closed as the corresponding pull request has been merged.
